# Generated by Django 3.0.1 on 2020-02-04 01:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('id_card', models.CharField(max_length=30, unique=True, verbose_name='DNI')),
                ('first_name', models.CharField(max_length=210, verbose_name='nombres')),
                ('last_name', models.CharField(max_length=210, verbose_name='apellido')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='fecha de nacimiento')),
                ('biography', models.TextField(blank=True, max_length=1200, null=True, verbose_name='biography')),
                ('movile_number', models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message='Phone numbermust be entered in the format: +99999999. Up to 15 digits allowed.', regex='\\+?1?\\d{9,15}$')], verbose_name='celular')),
                ('telephone_number', models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message='Phone numbermust be entered in the format: +99999999. Up to 15 digits allowed.', regex='\\+?1?\\d{9,15}$')], verbose_name='teléfono')),
            ],
            options={
                'verbose_name': 'persona',
                'verbose_name_plural': 'personas',
                'ordering': ['last_name', 'first_name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('street', models.CharField(max_length=50, verbose_name='calle')),
                ('number_street', models.CharField(max_length=18, verbose_name='número')),
                ('floor', models.CharField(blank=True, max_length=18, null=True, verbose_name='piso')),
                ('departament', models.CharField(blank=True, max_length=18, null=True, verbose_name='departamento')),
                ('type_address', models.CharField(choices=[('Residence', 'Residence')], default='Residence', max_length=12, verbose_name='tipo de residencia')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.City', verbose_name='ciudad')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persons.Person')),
            ],
            options={
                'verbose_name': 'dirección',
                'verbose_name_plural': 'direcciones',
                'ordering': ['street', 'number_street'],
            },
        ),
    ]
