# Generated by Django 3.0.1 on 2020-02-04 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('name', models.CharField(help_text='Nombre', max_length=70, unique=True, verbose_name='nombre')),
                ('slug_name', models.CharField(help_text='Slug name', max_length=70, unique=True, verbose_name='slug name')),
            ],
            options={
                'verbose_name': 'provincia',
                'verbose_name_plural': 'provincias',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='nombre')),
                ('zip_city', models.CharField(blank=True, max_length=30, null=True, verbose_name='código postal')),
                ('ddn', models.CharField(blank=True, max_length=12, null=True, verbose_name='característica')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.State')),
            ],
            options={
                'verbose_name': 'ciudad',
                'verbose_name_plural': 'ciudades',
                'ordering': ['name'],
            },
        ),
    ]
