# Generated by Django 3.0.1 on 2020-02-04 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='slug_name',
            field=models.CharField(blank=True, help_text='Slug name', max_length=70, unique=True, verbose_name='slug name'),
        ),
    ]
