# Generated by Django 3.0.1 on 2020-02-06 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_auto_20200203_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='slug_name',
            field=models.CharField(blank=True, help_text='Slug name', max_length=70, unique=True, verbose_name='slug name'),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=70, unique=True, verbose_name='nombre'),
        ),
    ]
